name: 'test'

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - README.md
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print hello
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
          echo ${{ github.ref_name }}
      - name: Print goodbye
        if: github.event.pull_request.merged == true && github.ref_name == 'main'
        run: |
          echo goodbye.
